# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15b7d3544c162f318a21856accb2ed156c0867b96b09423a984d636c8c10047dc3988af55e068cb25af54a113b2d39da8114513147e68663baa9c25cec635a92

test:
  secret_key_base: d24cd26f622cef13ceb96e02f42c51983ff5daff18873e5b00e1863e67dde9224ee8278727b9e8f2ddc28513c4a364dd680f5de019b8ed77e19541e536a6f54f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
